= FlowLogix MirrorImmich
:toc: macro
:toc-title: Table of Contents

FlowLogix MirrorImmich extracts title, description, tags, GPS location and album information created in Apple macOS Photos and creates a directory that includes symlinks to photos and their extracted metadata in sidecar .xmp files.

This directory can then be rsync'd to Immich external library.

MirroImmich needs to be run on a Mac with access to the Photos library. All photos need to be downloaded locally from iCloud (if iCloud is being used) for metadata extraction to work correctly.

== Features

* Creates a directory structure to be used as an external library in Immich.
* Exports titles, descriptions, GPS location, and keywords / tags.
** _Note: Appends titles and descriptions, since Immich only has one description field._
* Generates `.xmp` sidecar files.
* Exports edited photos, if they are edited.
* Creates albums in Immich based on Apple Photos albums.
* Marks favorites in Immich based on Apple Photos favorites.

== Installation
Docker Compose is the recommended installation method.

You can create `.env` file with the following variables:
[source,dotenv]
----
IMMICH_API_URL=https://my.immich.instance
IMMICH_API_KEY=<my_immich_api_key>

# Override default photos library location and names if needed
# PICTURES_DIRECTORY=${HOME}/Pictures
# PHOTOS_LIBRARY_NAME=Photos Library
# EXTRACTED_PHOTOS_NAME=extracted-photos
----

NOTE: Docker needs to have "full disk access" to be able to read Photos library

== Official web site
https://flowlogix.com/mirror-immich.html[Mirror Immich web site]

== MirrorImmich vs. Immich Go, PhotoSync, etc.
There are existing solutions for uploading photos to Immich.
However, none of those solutions access Apple macOS Photos internal database to extract metadata that was entered into Apple Photos on the Mac.
All other solutions extract data from the metadata from the photo and video files themselves. Unfortunately that data is incomplete and does not include manually entered data in Apple Photos on the Mac.

== Screenshots

Here is the configuration screen: +
https://photos.flowlogix.com/share/D-1UluOb68QTV_CVIU4VJstM6b57BmP4gd-Nw01FMTodR_t-BvlLWqHI-osEWNRaIEA/photos/c6ac47ba-c5f9-4edb-bee3-770bad2b3c8f[Configuration Screen]

Here is the result screen from a test run. As you can see, the results are read from the Photos SQLite database: +
https://photos.flowlogix.com/share/D-1UluOb68QTV_CVIU4VJstM6b57BmP4gd-Nw01FMTodR_t-BvlLWqHI-osEWNRaIEA/photos/04b9e182-6236-4781-a117-fb901335154f[Result Screen]

=== Metadata Comparison

**Apple Photos Info Panel:** +
As you can see, it is marked as Favorite. It has a title, description, and keywords. With iCloud and almost all other services, only "my description" gets transferred. Some will take keywords, but none transfer all metadata. +
https://photos.flowlogix.com/share/D-1UluOb68QTV_CVIU4VJstM6b57BmP4gd-Nw01FMTodR_t-BvlLWqHI-osEWNRaIEA/photos/605b3d12-3726-4c26-afc0-6c5ad1cc9398[Photos Info Panel]

**Desired Result in Immich:** +
The Photos title and description are combined into Immich's description field. +
https://photos.flowlogix.com/share/D-1UluOb68QTV_CVIU4VJstM6b57BmP4gd-Nw01FMTodR_t-BvlLWqHI-osEWNRaIEA/photos/f8e4b545-6897-490c-a8d0-81072ad405bd[Immich Result]

**Tags in Immich:** +
https://photos.flowlogix.com/share/D-1UluOb68QTV_CVIU4VJstM6b57BmP4gd-Nw01FMTodR_t-BvlLWqHI-osEWNRaIEA/photos/3301dc0a-e89e-485c-a76e-c308660feb97[Immich Tags]

== Contributing

If anybody is interested in it and/or wants to help me finish it up (or has any other feedback), please let me know.

== The Story
Over the past year, I have been battling with properly exporting and syncing my Apple Photos on the Mac (33k of them) with Immich. I have tried about 40 options that exist now. Nothing works 100%.

The problem is that macOS Photos stores all metadata in a SQLite database, and not in the photo/video files themselves. That database schema is complex and often messy. Since this metadata isn't 100% compatible with Immich, it needs to be processed before being put into `.xmp` sidecar files. This is where existing options fall short, often failing to preserve 100% of the metadata.

MirrorImmich is a custom exporter developed to solve this specific problem.
